/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecondOpinionRouteImport } from './routes/second-opinion'
import { Route as Home2RouteImport } from './routes/home-2'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondOpinionRoute = SecondOpinionRouteImport.update({
  id: '/second-opinion',
  path: '/second-opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const Home2Route = Home2RouteImport.update({
  id: '/home-2',
  path: '/home-2',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-2': typeof Home2Route
  '/second-opinion': typeof SecondOpinionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-2': typeof Home2Route
  '/second-opinion': typeof SecondOpinionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-2': typeof Home2Route
  '/second-opinion': typeof SecondOpinionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/home-2'
    | '/second-opinion'
    | '/sitemap.xml'
    | '/treatments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/home-2'
    | '/second-opinion'
    | '/sitemap.xml'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/home-2'
    | '/second-opinion'
    | '/sitemap.xml'
    | '/treatments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  Home2Route: typeof Home2Route
  SecondOpinionRoute: typeof SecondOpinionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TreatmentsRoute: typeof TreatmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-opinion': {
      id: '/second-opinion'
      path: '/second-opinion'
      fullPath: '/second-opinion'
      preLoaderRoute: typeof SecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-2': {
      id: '/home-2'
      path: '/home-2'
      fullPath: '/home-2'
      preLoaderRoute: typeof Home2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  Home2Route: Home2Route,
  SecondOpinionRoute: SecondOpinionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TreatmentsRoute: TreatmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
